# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests with JUnit as reporter
          command: JEST_JUNIT_OUTPUT_DIR=./test-results/jest yarn test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_artifacts:
          path: ./coverage/lcov-report
          prefix: coverage
      - run: yarn lint --format junit --output-file ./test-results/eslint/eslint.xml
      - store_test_results:
          path: test-results
